MileStone 8: Integration specs
Efiamotu-1/blog-rails-mv pull request #8
Opened 2023-01-31 02:13 UTC by Efiamotu-1

> ### ACTIVITIES
> * Make sure that the N+1 problem is solved when fetching all posts and their comments for a user. This is the corresponding wireframe
> * Integration specs
>   
>   * Use Capybara to write integration tests for each view in your project.
>   * For user index page
>   * For user show page
>   * For user post index page
>   * For user post show page

**Before n + 1**
![before-C](https://user-images.githubusercontent.com/89055502/215904259-bdd6121a-8293-4854-9e82-654dcbc15b3c.png)

![before-U](https://user-images.githubusercontent.com/89055502/215904278-9ae76dc9-c047-466b-a5df-43eb0cd16793.png)

**After n + 1**
![after-C](https://user-images.githubusercontent.com/89055502/215904341-ffacc594-43a5-4aab-9d05-2343069fa69b.png)
![after-U](https://user-images.githubusercontent.com/89055502/215904355-b753e85e-3388-4780-9619-868560ad06a5.png)

2023-01-31 03:38 UTC, rloterh reviewed
Hi Efyamotu, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your project adhere(s) to the following standard(s):
- [x] Do not use the bullet gem
- [ ] Add screenshots of the logs before and after the fix of the _(N + 1)_ problem.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-31 23:38 UTC, Lucas-Masaba requested changes
# Hello @Efiamotu-1 and @jdbs9514  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks passing ✔️ 
- Solved n+1 problems ⚡ 
- Tests are passing 🏄 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-31 23:38 UTC, Lucas-Masaba commented on spec/integration/user_show_spec.rb
> +  end
- [ ] As mentioned in the requirements, please add test(s) that asserts you can see the user's profile picture

2023-01-31 23:38 UTC, Lucas-Masaba commented on spec/integration/post_index_spec.rb
> +  end
- [ ] You are missing the following tests:
- Test(s) that asserts you can see the user's profile picture.
- Test(s) that redirects to the post's show page when you click on a post.

2023-02-01 02:03 UTC, cwaku approved these changes
Hi @Efiamotu-1 

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
 - [x] Correct GitHub Flow 👍🏾 
 - [x] Good commit history 🥇 
 - [x] Good PR title/description 💯 
 - [x] All linters passed 🥇 
 
![](https://media.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. The previous reviewer simply missed some of them, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-01 02:07 UTC, merged